export const randomTexts = [
    'Wow, this is amazing!',
    'LOL',
    'What just happened?',
    'This is so cool!',
    'I love this!',
    'OMG!',
    'No way!',
    'This is fire! 🔥',
    'Hahaha, I can’t stop laughing!',
    'This is the best thing ever!',
    'Let gooo! 🚀',
    'This is awesome!',
    'Something is not okay...',
    'Joined the chat! 👋',
    'Removed from the chat.',
    'Deleted the message.',
    'Banned from the chat.',
    'Welcome to the stream! 🎉',
    'Why is this happening?',
    'Im outta here!',
    'Can we get some hype?',
    'This is so chaotic!',
    'Im here for the vibes!',
    'Whats the plan?',
    'Lets make this epic!',
    'Im confused...',
    'This is wild!',
    'Im loving the energy! ⚡',
    'Can we take a break?',
    'This is getting intense!',
    'Im here for the memes! 🐸',
    'What next?',
    'This is pure gold!',
    'Im speechless...',
    'This is a vibe!',
    'Lets keep it going!',
    'Im here for the drama! 🍿',
    'This is too much!',
    'Im here for the laughs!',
    'This is legendary!',
    'Im here for the chaos!',
    'This is unreal!',
    'Im here for the fun!',
    'This is next level!',
    'Im here for the hype!',
    'This is insane!',
    'Im here for the energy!',
    'This is a rollercoaster!',
    'Im here for the ride!',
    'This is a masterpiece!',
    'Im here for the show!',
    'Is anyone else seeing this?',
    'That was unexpected!',
    'Can someone explain this?',
    'Absolute madness right now!',
    'This is so underrated!',
    'Im dying of laughter!',
    'Where did that come from?',
    'I cant believe my eyes!',
    'This is breaking the internet!',
    'How is this even possible?',
    'Someone clip that moment!',
    'This deserves an award!',
    'I need a replay of that!',
    'This is history in the making!',
    'Who else is losing it right now?',
    'Did that just happen live?',
    'I need to process this...',
    'This stream is unmatched!',
    'Epic moment alert! 🚨',
    'Can we talk about that?',
    'This is why I love the internet!',
    'What did I just witness?',
    'This is out of control!',
    'Can someone timestamp that?',
    'This is peak entertainment!',
    'My jaw is on the floor!',
    'Can we take a moment to appreciate this?',
    'This stream is a whole movie!',
    'How did we get here?',
    'This energy is infectious!',
    'Stream goals right here!',
    'The chat is going wild!',
    'This is meme material!',
    'I need popcorn for this! 🍿',
    'We need a compilation of this!',
    'This is stream gold!',
    'Who else is vibing hard?',
    'This is giving me life!',
    'This is an emotional rollercoaster!',
    'Someone make this into a GIF!',
    'This is better than TV!',
    'What a plot twist!',
    'This stream is iconic!',
    'That was savage!',
    'This deserves a standing ovation! 👏',
    'Stream of the year right here!',
    'That was pure chaos!',
    'This is stream perfection!',
    'I cant keep up!',
    'The suspense is killing me!',
    'That was a power move!',
    'Im living for this moment!',
    'This is internet gold!',
    'This is a certified classic!',
    'What the next surprise?',
    'Stream legends in the making!',
    'This is a cinematic experience!',
    'This is too good to be true!',
    'Im hooked!',
    'This is the content I signed up for!',
  ];



  export const randomUsernames = [
    'Ivy', 'Jack', 'Kara', 'Liam', 'Mia', 'Nate', 'Olivia', 'Pete', 'Quinn', 'Riley',
    'Sam', 'Tina', 'Uma', 'Victor', 'Wendy', 'Xander', 'Yara', 'Zane', 'Aiden', 'Bella',
    'Caleb', 'Delilah', 'Elliot', 'Fiona', 'Gavin', 'Hazel', 'Ian', 'Jade', 'Kai', 'Lila',
    'Mason', 'Nova', 'Oscar', 'Piper', 'Quincy', 'Ruby', 'Sebastian', 'Talia', 'Uriah', 'Vera',
    'Willow', 'Xenia', 'Yvette', 'Zara', 'Asher', 'Blake', 'Cora', 'Derek', 'Elena', 'Felix',
    'Gianna', 'Hunter', 'Isla', 'Jasper', 'Kelsey', 'Logan', 'Mila', 'Noah', 'Olive', 'Parker',
    'Quinn', 'Ryan', 'Sophia', 'Theo', 'Ulysses', 'Violet', 'Wesley', 'Ximena', 'Yvonne', 'Zeke'
  ];
  